name: Update Manifest

on:
  schedule:
    - cron: '10 * * * *'
    - cron: '25 * * * *'
    - cron: '40 * * * *'
    - cron: '55 * * * *'

  workflow_dispatch:

concurrency:
  group: download
  cancel-in-progress: false

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout MU repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          repository: pjy612/MU
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
          
      - name: Get Git SHA
        id: git_sha
        run: |
          echo "MU_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Print Git SHA
        run: |
          echo "The MU repository latest SHA is ${{ env.MU_SHA }}"
          echo "Git SHA is ${{ steps.git_sha.outputs.sha }}"
        
      - name: Fetch Manifest Repo
        run: |
          #git remote add manifest https://github.com/P-ToyStore/SteamManifestCache_Pro
          #git fetch --depth 1 --tags manifest
      - name: Fetch Manifest Repo Again
        run: |
          #git fetch --tags manifest -f
      - name: Fetch Repo
        run: |
          git fetch origin -f
          
      - name: Set Git Author
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@github.com
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 9.x
          cache: true

      - name: Restore previous build
        uses: actions/cache@v4
        id: binaries
        with:
          path: |
            bin/
            obj/
          key: ${{ runner.os }}-bin-${{ env.MU_SHA }}

      - name: Build manifest downloader
        if: steps.binaries.outputs.cache-hit != 'true'
        run: dotnet build --configuration Release /clp:ErrorsOnly

      - name: Download manifest
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: dotnet run --no-build --configuration Release /clp:ErrorsOnly

